<?php

declare(strict_types=1);

/**
 * Rotating exercise templates; theme/course strings are stitched in course_payloads.php.
 *
 * @return list<array<string, mixed>>
 */
return [
    [
        'phrases' => [
            ['text' => 'Could you help me, please?', 'translation' => 'Не могли бы вы помочь?'],
            ['text' => 'I am looking for…', 'translation' => 'Я ищу…'],
            ['text' => 'How much does it cost?', 'translation' => 'Сколько стоит?'],
            ['text' => 'Where is the nearest…?', 'translation' => 'Где ближайший…?'],
            ['text' => 'Thank you for your time.', 'translation' => 'Спасибо за уделённое время.'],
        ],
        'scramble_words' => ['Please', 'Sorry', 'Excuse', 'Thanks', 'Welcome'],
        'theory_header' => 'Politeness markers',
        'theory_paragraph' => 'Short requests with “could” and “please” sound friendly. You do not need long sentences at lower levels.',
        'quote' => 'Courtesy costs nothing but buys everything.',
        'quote_author' => 'Hazrat Inayat Khan',
        'speech_phrase' => 'Excuse me, could you help me for a moment?',
        'pairs_lr' => [['Please', 'Softens a request'], ['Sorry', 'You apologise'], ['Thanks', 'You show gratitude'], ['Hello', 'You greet someone']],
        'lw' => ['Please', 'Thanks'],
        'fill_gaps_text' => '[GAP] me, where is the ticket [GAP]?',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['Excuse', 'Pardon'], 'hint' => 'Polite attention-getter'],
            ['position' => 1, 'correctAnswers' => ['office', 'counter', 'desk'], 'hint' => 'Place to buy tickets'],
        ],
        'guess_items' => [
            ['word' => 'Queue', 'hint' => 'British word for a line of people waiting.'],
            ['word' => 'Restroom', 'hint' => 'Neutral word for a public toilet in the US.'],
        ],
        'cat_a_name' => 'Polite', 'cat_a_color' => '#1565c0',
        'cat_b_name' => 'Direct', 'cat_b_color' => '#c62828',
        'cat_rows' => [['Could you open the door?', 'A'], ['Open that door now.', 'B'], ['Would you mind waiting?', 'A'], ['Wait.', 'B']],
        'quiz_questions' => [
            ['text' => 'Which sounds more polite?', 'options' => ['Give me water', 'Could I have some water, please?'], 'correctOptions' => [1]],
            ['text' => '“Excuse me” often starts…', 'options' => ['a fight', 'a polite interruption', 'a song'], 'correctOptions' => [1]],
            ['text' => '“Thank you” fits when…', 'options' => ['someone helps you', 'you ignore someone', 'you are alone'], 'correctOptions' => [0]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'Turn left at the corner.', 'translation' => 'Поверните налево на углу.'],
            ['text' => 'Go straight ahead.', 'translation' => 'Идите прямо.'],
            ['text' => 'It is opposite the bank.', 'translation' => 'Это напротив банка.'],
            ['text' => 'Is it far on foot?', 'translation' => 'Далеко пешком?'],
            ['text' => 'You cannot miss it.', 'translation' => 'Вы его не проходите.'],
        ],
        'scramble_words' => ['Bridge', 'Corner', 'Station', 'Square', 'Tunnel'],
        'theory_header' => 'Prepositions of place',
        'theory_paragraph' => '“Next to”, “between”, and “opposite” are high-frequency. Pair them with a landmark people know.',
        'quote' => 'Not all those who wander are lost.',
        'quote_author' => 'J.R.R. Tolkien',
        'speech_phrase' => 'How do I get to the museum from here?',
        'pairs_lr' => [['Map', 'Shows streets'], ['Sign', 'Shows names or rules'], ['Landmark', 'Helps you navigate'], ['Detour', 'A different temporary route']],
        'lw' => ['Bridge', 'Square'],
        'fill_gaps_text' => 'Walk [GAP] the park, then turn [GAP] at the lights.',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['past', 'through', 'around'], 'hint' => 'Movement relative to the park'],
            ['position' => 1, 'correctAnswers' => ['left', 'right'], 'hint' => 'Direction at lights'],
        ],
        'guess_items' => [
            ['word' => 'Roundabout', 'hint' => 'Circular road junction common in the UK.'],
            ['word' => 'Pedestrian', 'hint' => 'A person walking, not driving.'],
        ],
        'cat_a_name' => 'Question', 'cat_a_color' => '#6a1b9a',
        'cat_b_name' => 'Answer', 'cat_b_color' => '#2e7d32',
        'cat_rows' => [['Where is the exit?', 'A'], ['Next to the café.', 'B'], ['Is it far?', 'A'], ['Five minutes.', 'B']],
        'quiz_questions' => [
            ['text' => '“Opposite” means…', 'options' => ['underground only', 'across from', 'inside'], 'correctOptions' => [1]],
            ['text' => 'A landmark is…', 'options' => ['invisible gas', 'a recognisable place', 'a kind of bus ticket'], 'correctOptions' => [1]],
            ['text' => '“Straight ahead” tells you…', 'options' => ['turn three times', 'continue without turning', 'go backwards'], 'correctOptions' => [1]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'I would like a coffee, please.', 'translation' => 'Я хотел бы кофе, пожалуйста.'],
            ['text' => 'For here or to go?', 'translation' => 'Здесь или с собой?'],
            ['text' => 'Can I pay by card?', 'translation' => 'Можно картой?'],
            ['text' => 'The bill, please.', 'translation' => 'Счёт, пожалуйста.'],
            ['text' => 'Is service included?', 'translation' => 'Чаевые включены?'],
        ],
        'scramble_words' => ['Menu', 'Order', 'Tip', 'Receipt', 'Sugar'],
        'theory_header' => 'Ordering food',
        'theory_paragraph' => 'Staff often ask binary questions. A short answer plus “please” keeps the line moving.',
        'quote' => 'People who love to eat are always the best people.',
        'quote_author' => 'Julia Child',
        'speech_phrase' => 'I would like the soup and a glass of water, please.',
        'pairs_lr' => [['Starter', 'First small dish'], ['Main course', 'Biggest dish'], ['Dessert', 'Sweet course'], ['Bill', 'Payment total']],
        'lw' => ['Order', 'Menu'],
        'fill_gaps_text' => 'Could we see the [GAP], please? I prefer still [GAP].',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['menu'], 'hint' => 'List of dishes'],
            ['position' => 1, 'correctAnswers' => ['water', 'sparkling'], 'hint' => 'Drink type'],
        ],
        'guess_items' => [
            ['word' => 'Allergen', 'hint' => 'A substance that can cause allergy.'],
            ['word' => 'Gratuity', 'hint' => 'Another word for a tip.'],
        ],
        'cat_a_name' => 'Customer', 'cat_a_color' => '#0277bd',
        'cat_b_name' => 'Server', 'cat_b_color' => '#ef6c00',
        'cat_rows' => [['What would you like to drink?', 'B'], ['Just water, thanks.', 'A'], ['Anything else?', 'B'], ['No, that is all.', 'A']],
        'quiz_questions' => [
            ['text' => '“To go” means…', 'options' => ['eat inside only', 'take away', 'cook at home'], 'correctOptions' => [1]],
            ['text' => '“I would like…” is…', 'options' => ['rude', 'polite for orders', 'only for lawyers'], 'correctOptions' => [1]],
            ['text' => 'The bill is…', 'options' => ['a free gift', 'what you pay', 'a type of fish'], 'correctOptions' => [1]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'I have a reservation under Smith.', 'translation' => 'Бронь на имя Смит.'],
            ['text' => 'What time is check-out?', 'translation' => 'Во сколько выселение?'],
            ['text' => 'The Wi-Fi password does not work.', 'translation' => 'Пароль Wi-Fi не работает.'],
            ['text' => 'Could we have extra towels?', 'translation' => 'Можно дополнительные полотенца?'],
            ['text' => 'Is breakfast included?', 'translation' => 'Завтрак включён?'],
        ],
        'scramble_words' => ['Lobby', 'Suite', 'Elevator', 'Luggage', 'Keycard'],
        'theory_header' => 'Hotel requests',
        'theory_paragraph' => 'State the problem calmly plus the room number. Reception staff solve dozens of similar issues daily.',
        'quote' => 'Hospitality is making your guests feel like they are at home, even if you wish they were.',
        'quote_author' => 'Gene Perret',
        'speech_phrase' => 'I have a booking for two nights.',
        'pairs_lr' => [['Check-in', 'Arrival procedure'], ['Check-out', 'Leaving and paying'], ['Housekeeping', 'Cleans rooms'], ['Concierge', 'Helps with tickets']],
        'lw' => ['Lobby', 'Suite'],
        'fill_gaps_text' => 'Our room is on the third [GAP]. The [GAP] is too noisy at night.',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['floor', 'level'], 'hint' => 'Height in the building'],
            ['position' => 1, 'correctAnswers' => ['street', 'traffic', 'aircon'], 'hint' => 'Possible disturbance'],
        ],
        'guess_items' => [
            ['word' => 'Twin room', 'hint' => 'Two single beds.'],
            ['word' => 'Deposit', 'hint' => 'Money held until you leave.'],
        ],
        'cat_a_name' => 'Request', 'cat_a_color' => '#00897b',
        'cat_b_name' => 'Response', 'cat_b_color' => '#5e35b1',
        'cat_rows' => [['Could you fix the shower?', 'A'], ['We will send maintenance.', 'B'], ['Is parking free?', 'A'], ['It is ten euros per day.', 'B']],
        'quiz_questions' => [
            ['text' => 'Check-out is when you…', 'options' => ['arrive only', 'leave and settle the bill', 'book online'], 'correctOptions' => [1]],
            ['text' => 'Housekeeping mainly…', 'options' => ['flies planes', 'cleans guest rooms', 'cooks dinner'], 'correctOptions' => [1]],
            ['text' => 'A key card often…', 'options' => ['opens the room door', 'starts a taxi', 'is lunch'], 'correctOptions' => [0]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'Boarding will begin shortly.', 'translation' => 'Посадка скоро начнётся.'],
            ['text' => 'Your gate has changed.', 'translation' => 'Ваш выход изменился.'],
            ['text' => 'Please have your passport ready.', 'translation' => 'Паспорт должен быть готов.'],
            ['text' => 'This flight is delayed.', 'translation' => 'Рейс задержан.'],
            ['text' => 'Place your bag in the overhead bin.', 'translation' => 'Положите сумку на полку над сиденьем.'],
        ],
        'scramble_words' => ['Gate', 'Delay', 'Boarding', 'Customs', 'Terminal'],
        'theory_header' => 'Airport listening',
        'theory_paragraph' => 'Announcements repeat numbers and place names. Write down digits you hear to reduce stress.',
        'quote' => 'The journey of a thousand miles begins with a single step.',
        'quote_author' => 'Lao Tzu',
        'speech_phrase' => 'Which gate is the flight to Berlin?',
        'pairs_lr' => [['Boarding pass', 'You show it to board'], ['Carry-on', 'Bag in the cabin'], ['Checked bag', 'Bag in the hold'], ['Transit', 'Changing planes']],
        'lw' => ['Gate', 'Delay'],
        'fill_gaps_text' => 'Flight AB nine nine is [GAP] by forty minutes. New [GAP] is twelve B.',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['delayed'], 'hint' => 'Not on time'],
            ['position' => 1, 'correctAnswers' => ['gate', 'departure'], 'hint' => 'Where you board'],
        ],
        'guess_items' => [
            ['word' => 'Layover', 'hint' => 'Waiting time between connecting flights.'],
            ['word' => 'Jet lag', 'hint' => 'Tiredness after crossing time zones.'],
        ],
        'cat_a_name' => 'Before flight', 'cat_a_color' => '#1e88e5',
        'cat_b_name' => 'Problem', 'cat_b_color' => '#e53935',
        'cat_rows' => [['Print boarding pass', 'A'], ['Lost luggage', 'B'], ['Arrive two hours early', 'A'], ['Cancelled connection', 'B']],
        'quiz_questions' => [
            ['text' => 'A delayed flight…', 'options' => ['leaves early', 'leaves later than planned', 'never lands'], 'correctOptions' => [1]],
            ['text' => 'Gate number tells you…', 'options' => ['where to board', 'your seat letter only', 'meal choice'], 'correctOptions' => [0]],
            ['text' => 'Customs checks…', 'options' => ['only music taste', 'goods and documents at borders', 'hotel stars'], 'correctOptions' => [1]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'I am writing to follow up on…', 'translation' => 'Пишу, чтобы уточнить…'],
            ['text' => 'Please find attached…', 'translation' => 'Во вложении…'],
            ['text' => 'Could we schedule a call?', 'translation' => 'Можем назначить звонок?'],
            ['text' => 'Let me know if you need more detail.', 'translation' => 'Напишите, если нужны детали.'],
            ['text' => 'Kind regards,', 'translation' => 'С уважением,'],
        ],
        'scramble_words' => ['Subject', 'Attachment', 'Thread', 'Recipient', 'Deadline'],
        'theory_header' => 'Email clarity',
        'theory_paragraph' => 'Put the main request in the first screen of text. Busy readers may not scroll.',
        'quote' => 'The single biggest problem in communication is the illusion that it has taken place.',
        'quote_author' => 'George Bernard Shaw',
        'speech_phrase' => 'I am writing to request a short update on the budget.',
        'pairs_lr' => [['Subject line', 'Topic of the email'], ['CC', 'Visible copy'], ['BCC', 'Hidden copy'], ['Signature', 'Closing block']],
        'lw' => ['Subject', 'Deadline'],
        'fill_gaps_text' => 'I am writing [GAP] regard to your email. Could you reply [GAP] Friday?',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['with', 'in'], 'hint' => 'Fixed phrase'],
            ['position' => 1, 'correctAnswers' => ['by', 'before'], 'hint' => 'Time limit'],
        ],
        'guess_items' => [
            ['word' => 'FYI', 'hint' => 'For your information.'],
            ['word' => 'Nudge', 'hint' => 'A gentle reminder message.'],
        ],
        'cat_a_name' => 'Formal', 'cat_a_color' => '#283593',
        'cat_b_name' => 'Informal', 'cat_b_color' => '#546e7a',
        'cat_rows' => [['Dear Sir or Madam,', 'A'], ['Hi team,', 'B'], ['Yours faithfully,', 'A'], ['Cheers,', 'B']],
        'quiz_questions' => [
            ['text' => 'A good subject line should…', 'options' => ['be empty', 'summarise the topic', 'hide the topic'], 'correctOptions' => [1]],
            ['text' => 'Attachments are mentioned when…', 'options' => ['you send files', 'you delete mail', 'you forget'], 'correctOptions' => [0]],
            ['text' => '“Kind regards” is…', 'options' => ['a closing phrase', 'a password', 'a virus'], 'correctOptions' => [0]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'Let us move to the next item.', 'translation' => 'Перейдём к следующему пункту.'],
            ['text' => 'I partially agree, however…', 'translation' => 'Частично согласен, однако…'],
            ['text' => 'Could we take this offline?', 'translation' => 'Можем обсудить отдельно?'],
            ['text' => 'Who owns the action point?', 'translation' => 'Кто отвечает за задачу?'],
            ['text' => 'We are short on time.', 'translation' => 'У нас мало времени.'],
        ],
        'scramble_words' => ['Agenda', 'Minutes', 'Quorum', 'Follow-up', 'Slide'],
        'theory_header' => 'Meeting moves',
        'theory_paragraph' => 'Signposting (“first, next, finally”) helps remote participants follow the thread.',
        'quote' => 'The art of communication is the language of leadership.',
        'quote_author' => 'James Humes',
        'speech_phrase' => 'I suggest we table this topic until next week.',
        'pairs_lr' => [['Agenda', 'Planned topics'], ['Minutes', 'Written record'], ['Chair', 'Runs the meeting'], ['Parking lot', 'Ideas saved for later']],
        'lw' => ['Agenda', 'Minutes'],
        'fill_gaps_text' => 'Let us [GAP] the decision until we have [GAP] from finance.',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['defer', 'postpone', 'delay'], 'hint' => 'Put off'],
            ['position' => 1, 'correctAnswers' => ['data', 'numbers', 'approval'], 'hint' => 'What finance provides'],
        ],
        'guess_items' => [
            ['word' => 'Stakeholder', 'hint' => 'Anyone with interest in the outcome.'],
            ['word' => 'Dial-in', 'hint' => 'Joining a call by phone.'],
        ],
        'cat_a_name' => 'Structure', 'cat_a_color' => '#3949ab',
        'cat_b_name' => 'Opinion', 'cat_b_color' => '#d84315',
        'cat_rows' => [['First, finance will present.', 'A'], ['I disagree with the timeline.', 'B'], ['We will wrap up in five minutes.', 'A'], ['In my view, the risk is high.', 'B']],
        'quiz_questions' => [
            ['text' => 'An action point is…', 'options' => ['a joke', 'a task for someone', 'a coffee break'], 'correctOptions' => [1]],
            ['text' => 'Minutes usually record…', 'options' => ['only jokes', 'decisions and owners', 'secret codes'], 'correctOptions' => [1]],
            ['text' => '“Let us park that” means…', 'options' => ['drive a car', 'save the topic for later', 'end the company'], 'correctOptions' => [1]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'The data suggests a trend.', 'translation' => 'Данные указывают на тренд.'],
            ['text' => 'We should mitigate the risk.', 'translation' => 'Нужно смягчить риск.'],
            ['text' => 'Evidence remains inconclusive.', 'translation' => 'Доказательства пока неубедительны.'],
            ['text' => 'Policy options include subsidies.', 'translation' => 'Варианты политики включают субсидии.'],
            ['text' => 'Citizens demand transparency.', 'translation' => 'Граждане требуют прозрачности.'],
        ],
        'scramble_words' => ['Policy', 'Evidence', 'Debate', 'Reform', 'Vote'],
        'theory_header' => 'Hedging claims',
        'theory_paragraph' => 'Words like “suggest”, “indicate”, and “tend to” keep you accurate when proof is partial.',
        'quote' => 'The only way to do great work is to love what you do.',
        'quote_author' => 'Steve Jobs',
        'speech_phrase' => 'The report indicates a gradual shift in public opinion.',
        'pairs_lr' => [['Legislature', 'Makes laws'], ['Executive', 'Implements policy'], ['Judiciary', 'Interprets law'], ['Referendum', 'Public vote on an issue']],
        'lw' => ['Policy', 'Debate'],
        'fill_gaps_text' => 'Analysts [GAP] that inflation will slow; they admit the [GAP] is uncertain.',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['predict', 'expect', 'forecast'], 'hint' => 'Say what may happen'],
            ['position' => 1, 'correctAnswers' => ['outcome', 'forecast', 'picture'], 'hint' => 'Result picture'],
        ],
        'guess_items' => [
            ['word' => 'Lobbyist', 'hint' => 'Someone who tries to influence politicians.'],
            ['word' => 'Mandate', 'hint' => 'Authority from voters to act.'],
        ],
        'cat_a_name' => 'Fact-style', 'cat_a_color' => '#1565c0',
        'cat_b_name' => 'Opinion-style', 'cat_b_color' => '#ef6c00',
        'cat_rows' => [['GDP grew two percent.', 'A'], ['This government is hopeless.', 'B'], ['Turnout was sixty percent.', 'A'], ['Only a fool would disagree.', 'B']],
        'quiz_questions' => [
            ['text' => 'Hedging helps you…', 'options' => ['sound arrogant', 'avoid overstating proof', 'delete grammar'], 'correctOptions' => [1]],
            ['text' => 'Evidence is…', 'options' => ['always the same as opinion', 'information supporting a claim', 'a type of cake'], 'correctOptions' => [1]],
            ['text' => 'A referendum is…', 'options' => ['private diary', 'a public vote on an issue', 'a weather report'], 'correctOptions' => [1]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'The sample size was small.', 'translation' => 'Выборка была мала.'],
            ['text' => 'Correlation is not causation.', 'translation' => 'Корреляция не равна причинности.'],
            ['text' => 'Peer review strengthens findings.', 'translation' => 'Рецензирование усиливает выводы.'],
            ['text' => 'The margin of error is plus minus three.', 'translation' => 'Погрешность плюс-минус три.'],
            ['text' => 'Further replication is needed.', 'translation' => 'Нужно дополнительное воспроизведение.'],
        ],
        'scramble_words' => ['Hypothesis', 'Method', 'Sample', 'Bias', 'Control'],
        'theory_header' => 'Reading studies',
        'theory_paragraph' => 'Check who funded the study, the sample, and whether results were pre-registered.',
        'quote' => 'In God we trust; all others must bring data.',
        'quote_author' => 'W. Edwards Deming',
        'speech_phrase' => 'We need a larger sample before we generalise.',
        'pairs_lr' => [['Hypothesis', 'Testable prediction'], ['Variable', 'Factor that changes'], ['Control group', 'Baseline for comparison'], ['Placebo', 'Inactive treatment for comparison']],
        'lw' => ['Sample', 'Bias'],
        'fill_gaps_text' => 'If the study is [GAP], the results may [GAP] certain groups.',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['biased', 'flawed'], 'hint' => 'Unfair design'],
            ['position' => 1, 'correctAnswers' => ['favour', 'miss', 'ignore'], 'hint' => 'Treat unevenly'],
        ],
        'guess_items' => [
            ['word' => 'Double-blind', 'hint' => 'Neither subjects nor staff know who gets what.'],
            ['word' => 'Confounder', 'hint' => 'A hidden variable that distorts results.'],
        ],
        'cat_a_name' => 'Methods', 'cat_a_color' => '#00695c',
        'cat_b_name' => 'Pitfalls', 'cat_b_color' => '#b71c1c',
        'cat_rows' => [['Random assignment used', 'A'], ['Cherry-picked graphs', 'B'], ['Preregistered analysis plan', 'A'], ['P-hacking suspected', 'B']],
        'quiz_questions' => [
            ['text' => 'A control group helps…', 'options' => ['increase noise', 'compare with a baseline', 'delete data'], 'correctOptions' => [1]],
            ['text' => 'Sample size affects…', 'options' => ['nothing', 'how confidently you generalise', 'only colours'], 'correctOptions' => [1]],
            ['text' => 'Correlation means…', 'options' => ['variables move together somehow', 'proof of cause', 'random typing'], 'correctOptions' => [0]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'The plot unfolds slowly.', 'translation' => 'Сюжет разворачивается медленно.'],
            ['text' => 'The cinematography is stunning.', 'translation' => 'Операторская работа потрясающая.'],
            ['text' => 'The score amplifies tension.', 'translation' => 'Музыка усиливает напряжение.'],
            ['text' => 'Subtitles helped me follow.', 'translation' => 'Субтитры помогли следить.'],
            ['text' => 'The finale divided critics.', 'translation' => 'Финал разделил критиков.'],
        ],
        'scramble_words' => ['Scene', 'Cast', 'Genre', 'Review', 'Audience'],
        'theory_header' => 'Review language',
        'theory_paragraph' => 'Balance summary (no spoilers) with judgement (why it worked or failed for you).',
        'quote' => 'Cinema is a mirror by which we often see ourselves.',
        'quote_author' => 'Martin Scorsese',
        'speech_phrase' => 'The pacing felt uneven in the second act.',
        'pairs_lr' => [['Protagonist', 'Main character'], ['Antagonist', 'Opposing force'], ['Subplot', 'Secondary storyline'], ['Sequel', 'Follow-up film']],
        'lw' => ['Review', 'Genre'],
        'fill_gaps_text' => 'The film blends [GAP] and comedy; some viewers found the [GAP] confusing.',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['drama', 'horror', 'action'], 'hint' => 'Serious or intense genre'],
            ['position' => 1, 'correctAnswers' => ['tone', 'plot', 'ending'], 'hint' => 'What felt unclear'],
        ],
        'guess_items' => [
            ['word' => 'MacGuffin', 'hint' => 'A plot device everyone chases but matters little itself.'],
            ['word' => 'Montage', 'hint' => 'A sequence of short shots showing passage of time.'],
        ],
        'cat_a_name' => 'Description', 'cat_a_color' => '#4527a0',
        'cat_b_name' => 'Judgement', 'cat_b_color' => '#c2185b',
        'cat_rows' => [['It runs for two hours.', 'A'], ['It is a masterpiece.', 'B'], ['Shot mostly at night.', 'A'], ['I would not recommend it.', 'B']],
        'quiz_questions' => [
            ['text' => 'A spoiler…', 'options' => ['helps surprise', 'reveals key plot points', 'is a camera'], 'correctOptions' => [1]],
            ['text' => 'Genre tells you…', 'options' => ['the ticket price only', 'the kind of story', 'the actor’s age'], 'correctOptions' => [1]],
            ['text' => 'Cinematography refers to…', 'options' => ['sound mixing only', 'camera work and lighting', 'popcorn sales'], 'correctOptions' => [1]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'Metaphor maps one domain onto another.', 'translation' => 'Метафора переносит одну сферу на другую.'],
            ['text' => 'The tone shifts from neutral to urgent.', 'translation' => 'Тон смещается к настойчивости.'],
            ['text' => 'Legal drafting avoids ambiguity.', 'translation' => 'Юридический стиль избегает двусмысленности.'],
            ['text' => 'We might tentatively conclude…', 'translation' => 'Мы можем осторожно заключить…'],
            ['text' => 'The author implies criticism.', 'translation' => 'Автор намекает на критику.'],
        ],
        'scramble_words' => ['Register', 'Nuance', 'Stance', 'Syntax', 'Cohesion'],
        'theory_header' => 'Precision',
        'theory_paragraph' => 'Advanced writers choose not only what to say but how strongly to say it.',
        'quote' => 'The difference between the right word and the almost right word is the difference between lightning and a lightning bug.',
        'quote_author' => 'Mark Twain',
        'speech_phrase' => 'The argument rests on an unstated assumption.',
        'pairs_lr' => [['Denotation', 'Dictionary meaning'], ['Connotation', 'Emotional colouring'], ['Euphemism', 'Milder wording'], ['Pejorative', 'Negative colouring']],
        'lw' => ['Nuance', 'Stance'],
        'fill_gaps_text' => 'The word [GAP] is pejorative here; a neutral alternative would be [GAP].',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['mob', 'regime', 'fanatic'], 'hint' => 'Loaded noun'],
            ['position' => 1, 'correctAnswers' => ['crowd', 'government', 'activist'], 'hint' => 'Neutral counterpart'],
        ],
        'guess_items' => [
            ['word' => 'Presupposition', 'hint' => 'Meaning taken for granted in an utterance.'],
            ['word' => 'Modality', 'hint' => 'Verbs like might, must, should showing certainty.'],
        ],
        'cat_a_name' => 'Literal', 'cat_a_color' => '#37474f',
        'cat_b_name' => 'Figurative', 'cat_b_color' => '#6a1b9a',
        'cat_rows' => [['The box weighs two kilos.', 'A'], ['Time is money.', 'B'], ['The meeting is at three.', 'A'], ['His voice was gravel and smoke.', 'B']],
        'quiz_questions' => [
            ['text' => 'Connotation is…', 'options' => ['exact dictionary definition', 'extra emotional sense', 'spelling'], 'correctOptions' => [1]],
            ['text' => 'Hedging in academic prose…', 'options' => ['always means lying', 'calibrates certainty', 'removes verbs'], 'correctOptions' => [1]],
            ['text' => 'A euphemism…', 'options' => ['is always rude', 'softens a blunt idea', 'is a number'], 'correctOptions' => [1]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'Moreover, the cost increased.', 'translation' => 'Более того, стоимость выросла.'],
            ['text' => 'Therefore we reject the null hypothesis.', 'translation' => 'Поэтому отвергаем нулевую гипотезу.'],
            ['text' => 'However, limitations remain.', 'translation' => 'Однако ограничения остаются.'],
            ['text' => 'In contrast, the rival model fits better.', 'translation' => 'В отличие от этого, соперничающая модель лучше подходит.'],
            ['text' => 'To summarise, three findings stand out.', 'translation' => 'Подводя итог, выделяются три находки.'],
        ],
        'scramble_words' => ['Therefore', 'However', 'Furthermore', 'Although', 'Hence'],
        'theory_header' => 'Connectives',
        'theory_paragraph' => 'Signalling how sentences relate reduces reader effort and strengthens argument flow.',
        'quote' => 'Meaning is use.',
        'quote_author' => 'Ludwig Wittgenstein',
        'speech_phrase' => 'Nevertheless, the evidence supports our main claim.',
        'pairs_lr' => [['Therefore', 'Shows result'], ['Although', 'Shows concession'], ['Furthermore', 'Adds a point'], ['In contrast', 'Shows difference']],
        'lw' => ['However', 'Therefore'],
        'fill_gaps_text' => 'The data are noisy; [GAP], the trend is clear. [GAP], we should replicate the study.',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['nevertheless', 'however', 'still'], 'hint' => 'Contrast despite noise'],
            ['position' => 1, 'correctAnswers' => ['Therefore', 'Thus', 'Hence'], 'hint' => 'Logical result'],
        ],
        'guess_items' => [
            ['word' => 'Anaphora', 'hint' => 'Pronoun pointing back to earlier noun.'],
            ['word' => 'Ellipsis', 'hint' => 'Omitted words the reader must infer.'],
        ],
        'cat_a_name' => 'Additive', 'cat_a_color' => '#455a64',
        'cat_b_name' => 'Adversative', 'cat_b_color' => '#ad1457',
        'cat_rows' => [['Furthermore, costs rose.', 'A'], ['Yet critics disagree.', 'B'], ['Additionally, we tested adults.', 'A'], ['Still, flaws persist.', 'B']],
        'quiz_questions' => [
            ['text' => '“Therefore” signals…', 'options' => ['random words', 'a conclusion or result', 'a greeting'], 'correctOptions' => [1]],
            ['text' => '“Although” introduces…', 'options' => ['a concession', 'a recipe', 'a price'], 'correctOptions' => [0]],
            ['text' => 'Cohesion helps…', 'options' => ['confuse readers', 'tie sentences together', 'remove punctuation'], 'correctOptions' => [1]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'Let me clarify what I meant.', 'translation' => 'Уточню, что имел в виду.'],
            ['text' => 'Could you paraphrase that?', 'translation' => 'Можете перефразировать?'],
            ['text' => 'I see your point, but…', 'translation' => 'Понимаю вашу мысль, но…'],
            ['text' => 'We might be talking past each other.', 'translation' => 'Мы, возможно, говорим мимо друг друга.'],
            ['text' => 'Let us agree on definitions first.', 'translation' => 'Сначала договоримся о терминах.'],
        ],
        'scramble_words' => ['Clarify', 'Nuance', 'Intent', 'Misread', 'Align'],
        'theory_header' => 'Repairing talk',
        'theory_paragraph' => 'Signalling misunderstanding early saves time and keeps rapport.',
        'quote' => 'We have two ears and one mouth so that we can listen twice as much as we speak.',
        'quote_author' => 'Epictetus',
        'speech_phrase' => 'I am not sure I follow—could you give an example?',
        'pairs_lr' => [['Clarify', 'Make meaning clearer'], ['Confirm', 'Check you understood'], ['Reframe', 'Restate from another angle'], ['Interrupt', 'Break into speech']],
        'lw' => ['Clarify', 'Intent'],
        'fill_gaps_text' => 'I think there is a [GAP]—when you said [GAP], did you mean the budget?',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['misunderstanding', 'confusion'], 'hint' => 'Problem in communication'],
            ['position' => 1, 'correctAnswers' => ['savings', 'cut', 'freeze'], 'hint' => 'Example word from their side'],
        ],
        'guess_items' => [
            ['word' => 'Backchannel', 'hint' => 'Short cues like “mm-hmm” while listening.'],
            ['word' => 'Face-threatening', 'hint' => 'Acts that can hurt someone’s dignity.'],
        ],
        'cat_a_name' => 'Cooperative', 'cat_a_color' => '#2e7d32',
        'cat_b_name' => 'Confrontational', 'cat_b_color' => '#c62828',
        'cat_rows' => [['Could we slow down a little?', 'A'], ['That is a stupid idea.', 'B'], ['Help me understand your concern.', 'A'], ['You always mess up.', 'B']],
        'quiz_questions' => [
            ['text' => 'Paraphrasing helps…', 'options' => ['guarantee anger', 'check understanding', 'delete listening'], 'correctOptions' => [1]],
            ['text' => '“Talking past each other” means…', 'options' => ['walking while talking', 'arguing different unstated points', 'silent agreement'], 'correctOptions' => [1]],
            ['text' => 'Defining terms first is useful when…', 'options' => ['words are vague or contested', 'everyone agrees already', 'no one speaks'], 'correctOptions' => [0]],
        ],
    ],
    [
        'phrases' => [
            ['text' => 'Once upon a time…', 'translation' => 'Давным-давно…'],
            ['text' => 'Suddenly everything changed.', 'translation' => 'Внезапно всё изменилось.'],
            ['text' => 'The twist caught me off guard.', 'translation' => 'Поворот застал врасплох.'],
            ['text' => 'In the end, they reconciled.', 'translation' => 'В конце они помирились.'],
            ['text' => 'I learned something about myself.', 'translation' => 'Я узнал что-то о себе.'],
        ],
        'scramble_words' => ['Plot', 'Twist', 'Climax', 'Moral', 'Scene'],
        'theory_header' => 'Story arcs',
        'theory_paragraph' => 'Even short anecdotes benefit from a clear turn: setup, shift, resolution.',
        'quote' => 'Stories can conquer fear, you know.',
        'quote_author' => 'Ben Okri',
        'speech_phrase' => 'The turning point came when she spoke up.',
        'pairs_lr' => [['Exposition', 'Background setup'], ['Rising action', 'Tension builds'], ['Climax', 'Peak conflict'], ['Resolution', 'Loose ends tied']],
        'lw' => ['Climax', 'Twist'],
        'fill_gaps_text' => 'The story [GAP] slowly, then the hero made a brave [GAP].',
        'fill_gaps' => [
            ['position' => 0, 'correctAnswers' => ['builds', 'unfolds'], 'hint' => 'How tension grows'],
            ['position' => 1, 'correctAnswers' => ['choice', 'decision', 'move'], 'hint' => 'Key action'],
        ],
        'guess_items' => [
            ['word' => 'Flashback', 'hint' => 'Scene from an earlier time inserted in the story.'],
            ['word' => 'Foreshadowing', 'hint' => 'Early hint of what will happen later.'],
        ],
        'cat_a_name' => 'Setup', 'cat_a_color' => '#1565c0',
        'cat_b_name' => 'Payoff', 'cat_b_color' => '#ef6c00',
        'cat_rows' => [['Introduced the characters', 'A'], ['The secret was revealed', 'B'], ['Described the ordinary day', 'A'], ['Justice was served', 'B']],
        'quiz_questions' => [
            ['text' => 'Climax is…', 'options' => ['the dullest line', 'the peak of tension', 'the title page'], 'correctOptions' => [1]],
            ['text' => 'A twist…', 'options' => ['never surprises', 'changes how you see the story', 'is only grammar'], 'correctOptions' => [1]],
            ['text' => 'Resolution usually…', 'options' => ['starts the fight', 'settles the outcome', 'deletes characters'], 'correctOptions' => [1]],
        ],
    ],
];
