services:
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ../docker/common/php-fpm/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-PHPSTORM}
        XDEBUG_LOG_LEVEL: 7
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/var/www
      - ../conf/php/uploads.ini:/usr/local/etc/php/conf.d/zz-uploads.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

  laravel-queue:
    container_name: laravel-queue
    build:
      context: ..
      dockerfile: docker/common/php-queue-worker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      STRIPE_WEBHOOK_FORWARD_TO: ${STRIPE_WEBHOOK_FORWARD_TO:-http://nginx:8080/api/stripe/webhook}
      STRIPE_SECRET: ${STRIPE_SECRET}
    volumes:
      - .:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

networks:
  app_network:
    external: true
